server:
  port: 8761
spring:
  application:
    name: micro-cloud-discover
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:    
    enableSelfPreservation: false  # false -> fastly refresh dead instances of microservices. Thus, it will wait for frequent heartbeats from instances



    