server:   
  port: 8080
  
spring:
  application:
    name: micro-api-ecommerce
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true    
    hibernate:
      ddl-auto: create-drop  # OPTIONS: none, validate, update, create-drop                              
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    
