server:
  port: 8001
front:
  url: http://localhost:4202        
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true    
    hibernate:
      ddl-auto: create-drop
    # none, validate, update, create-drop
    defer-datasource-initialization: true
  sql:
    init.mode: always                        
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
  h2:
    console.enabled: true
    # /h2-console