server:
  port: 8765
spring:
  application:
    name: micro-cloud-proxy
eureka:  
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
      
zuul:
  routes:
    ecommerce:
      path: /ecommerce/**
      service-id : micro-api-ecommerce
    back-office:      
      url : http://192.168.1.78:53220/
      #service-id: 192.168.199.1:61439/   


