server: 
  # if port = 0 eureka allows only one instance
  port: 8083
front:
  url: http://localhost:4202
spring:
  application:
    name: micro-api-ecommerce
  datasource:
    url: jdbc:h2:tcp://localhost:7001/mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false    
    hibernate:
      ddl-auto: validate
    # none, validate, update, create-drop                          
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2