server:   
  port: 8086

  
spring:
  application:
    name: micro-api-ecommerce-cloud
  datasource:
    #url: jdbc:h2:mem:mydb
    url: jdbc:h2:tcp://localhost:7001/mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate  # OPTIONS: none, validate, update, create-drop                              
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss  
  
  ##### SECURITY PROPERTIES #####
  # overrride user/pass instead default for basic login .formLogin() (user=user and pass genarateted on console)
  # OR, instead can be defined on UserDetailsService Bean
  security:    
    user:
      name: teste      
      password: 123         
  # RETIRA INICIALIZAÇÃO DAS DEPENENCIAS DE SEGURAÇANÇA SECURITY AUTOCONFIGURATION
  # (spring-boot-starter-security, e do spring-boot-starter-actuator)
  # o mesmo pode ser feito com @SpringBootApplication(exclude={...      
  #autoconfigure:
  #  exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  #  exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  
 
eureka:
  client:    
    enabled: false  # false : in cases when we dont want to connect to a Eureka service
    registerWithEureka: false  # false: in cases when we dont want to connect to a Eureka service
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30  # in combination of enableSelfPreservation defined in eureka server
    leaseExpirationDurationInSeconds: 5 # in combination of enableSelfPreservation defined in eureka server
    
    
  
# specific application custom properties  
app:
  services:
    payment:
      uri: http://localhost:8050/order-payment/
      
    
    

    

