server: 
  port: 0 
front:
  url: http://localhost:4202        
spring:
  application:
    name: micro-api-ecommerce1
  datasource:
    url: jdbc:h2:tcp://localhost:7001/mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false    
    hibernate:
      ddl-auto: validate
    # none, validate, update, create-drop                          
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8001/eureka}
  instance:
    preferIpAddress: true 