server:   
  port: 8050
  
spring:
  application:
    name: micro-api-finance
  datasource:    
    url: jdbc:h2:tcp://localhost:7001/mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate  # OPTIONS: none, validate, update, create-drop                              
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
  #h2:
  #  console.enabled: true  # Enables H2 browser page on: /h2-console       
        
eureka:
  client:    
    enabled: true  # false : in cases when we dont want to connect to a Eureka service
    registerWithEureka: true  # false: in cases when we dont want to connect to a Eureka service
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30  # in combination of enableSelfPreservation defined in eureka server
    leaseExpirationDurationInSeconds: 5 # in combination of enableSelfPreservation defined in eureka server


    

    

