spring:
  datasource:
    url: jdbc:h2:mem:mydb
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop  # OPTIONS: none, validate, update, create-drop
  h2:
    console.enabled: true  # Enables H2 browser page on: /h2-console

eureka:
  client:
    enabled: false  # false : in cases when we dont want to connect to a Eureka service
    registerWithEureka: false  # false: in cases when we dont want to connect to a Eureka service
