server:   
  port: 8050

spring:
  profiles:
   #active: standalone
   active: cloud-h2

  application:
    name: micro-api-finance
  datasource:    
    #url: defined on profile file
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    #generate-ddl: false
    #hibernate:
      #ddl-auto: validate  # OPTIONS: none, validate, update, create-drop
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
  #h2:
    #console.enabled: defined on profile file

eureka:
  client:    
    #enabled: defined on profile file 
    #registerWithEureka: defined on profile file 
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30  # in combination of enableSelfPreservation defined in eureka server
    leaseExpirationDurationInSeconds: 5 # in combination of enableSelfPreservation defined in eureka server
